#!/usr/bin/env bash
set -euo pipefail

# OpenClaw Deploy — Control Plane Installer
# Usage: curl -sSL https://openclaw-deploy.prin7r.com/install.sh | bash

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${GREEN}[Cold Iron]${NC} $1"; }
warn() { echo -e "${YELLOW}[Warning]${NC} $1"; }
error() { echo -e "${RED}[Error]${NC} $1"; exit 1; }

INSTALL_DIR="${COLD_IRON_INSTALL_DIR:-/opt/coldiron}"
REPO="https://github.com/prin7r-projects/openclaw-deploy"

log "OpenClaw Deploy — Cold Iron Control Plane Installer"
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || error "Docker is required. Install Docker first: https://docs.docker.com/get-docker/"
command -v docker compose >/dev/null 2>&1 || error "Docker Compose is required. Update Docker to get 'docker compose'."

# Create install directory
log "Installing to ${INSTALL_DIR}..."
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Clone or update repo
if [ -d ".git" ]; then
  log "Updating existing installation..."
  git pull origin main
else
  log "Cloning repository..."
  git clone "$REPO" .
fi

# Create data directory for SQLite
mkdir -p apps/api/data

# Generate environment file if it doesn't exist
if [ ! -f .env ]; then
  log "Generating environment configuration..."
  cat > .env <<'EOF'
# Cold Iron — Environment Configuration
# Generated by install.sh

# Database
DATABASE_URL=./apps/api/data/coldiron.db

# API
PORT=8787

# NOWPayments (get from https://nowpayments.io)
NOWPAYMENTS_API_KEY=
NOWPAYMENTS_IPN_SECRET=
NOWPAYMENTS_SANDBOX=false

# Secrets encryption
COLD_IRON_KEY_PASSPHRASE=CHANGE_ME_$(openssl rand -hex 16)

# Domain
DOMAIN=openclaw-deploy.prin7r.com
EOF
  warn "Created .env — edit NOWPAYMENTS keys and COLD_IRON_KEY_PASSPHRASE before starting"
fi

# Build and start
log "Building containers..."
docker compose build

log "Starting services..."
docker compose up -d

echo ""
log "${BOLD}Installation complete!${NC}"
echo ""
echo "  API:     http://localhost:8787"
echo "  Landing: http://localhost:3000"
echo "  Health:  http://localhost:8787/healthz"
echo ""
echo "  Next steps:"
echo "    1. Edit .env with your API keys"
echo "    2. Install the CLI: npm install -g @openclaw-deploy/occ"
echo "    3. Login: occ login -e your@email.com"
echo "    4. Apply a fleet: occ apply -f fleet.yaml"
echo ""
